🌱chore: update models associate
woocheonjae/HiRolling-Server pull request #16
Opened 2023-01-02 14:43 UTC by SollyJ

user테이블과 1:n관계인 테이블들 관계 설정 코드 추가했습니다.
PersonalRollingPaper(1) : PersonalPost(N) 관계 코드도 추가했습니다.

2023-01-02 14:47 UTC, j2woo approved these changes
확인했습니다.

2023-01-02 14:49 UTC, Hyyena commented on package.json
> +<<<<<<< Updated upstream
stash 과정에서 생긴 병합 코드를 지워주셔야 할 것 같습니다

2023-01-02 14:52 UTC, Hyyena commented on package.json
> +>>>>>>> Stashed changes
병합 과정에서 추가된 과거 코드인 것 같은데 삭제가 필요해보입니다.

2023-01-02 15:11 UTC, Hyyena requested changes
stash 적용이 잘 안돼서 수정해야 할 부분이 초큼 많을 것 같네여..ㅎㅎ

2023-01-02 15:11 UTC, Hyyena commented on package.json
> +    "typescript": "^4.9.4",
타입스크립트는 개발환경에만 필요하니 배포 환경 라이브러리에는 삭제해야할 것 같습니다.
현재 파일에서 devDependencis에 타입스크립트가 있습니다.

2023-01-02 15:11 UTC, Hyyena commented on package.json
> +<<<<<<< Updated upstream
삭제가 필요해보입니다.

2023-01-02 15:11 UTC, Hyyena commented on package.json
> +>>>>>>> Stashed changes
바로 위에 같은 라이브러리가 있어 삭제가 필요해보입니다.

2023-01-02 15:11 UTC, Hyyena commented on package.json
> +  ]
`tsconfig.json` 파일에 있는 내용이라 삭제해도 될 것 같습니다.

2023-01-02 15:11 UTC, Hyyena commented on src/models/user.ts
> +  Group: Group[];
다른 파일도 1:N 관계에서 변수명을 복수로 지정해줘서
`Groups`로 바꿔야 할 것 같습니다.

2023-01-02 15:11 UTC, Hyyena commented on src/models/user.ts
> +  GroupMember: GroupMember[];
`GroupMembers`로 바꿔야 할 것 같습니다.

2023-01-02 15:11 UTC, Hyyena commented on src/models/user.ts
> +  GroupPost: GroupPost[];
`GroupPosts`로 바꿔야 할 것 같습니다.

2023-01-02 15:11 UTC, Hyyena commented on src/models/user.ts
> +  PersonalPost: PersonalPost[];
`PersonalPosts`로 바꿔야 할 것 같습니다.

2023-01-02 15:11 UTC, Hyyena commented on yarn.lock
> +<<<<<<< Updated upstream
`yarn.lock` 파일도 다른 파일들과 마찬가지로 stash 병합 중에 생긴 메시지들 삭제가 필요해 보입니다.
라이브러리 겹쳐서 중복으로 생긴 것들은 `package.json`에서 삭제할 라이브러리 확인 후에  `yarn` 명령어로 지우면 지워질 것 같습니다.

2023-01-03 08:04 UTC, SollyJ commented on src/models/user.ts
> +  Group: Group[];
수정하겠습니다.

2023-01-03 08:04 UTC, SollyJ commented on src/models/user.ts
> +  GroupMember: GroupMember[];
수정하겠습니다.

2023-01-03 08:04 UTC, SollyJ commented on src/models/user.ts
> +  GroupPost: GroupPost[];
수정하겠습니다.

2023-01-03 08:51 UTC, Hyyena approved these changes
고생하셨습니다~

2023-01-03 08:52 UTC, wodb73 approved these changes

2023-01-03 09:00 UTC, merged