✨ feat(api): add api for create and view PRP
woocheonjae/HiRolling-Server pull request #25
Opened 2023-01-08 13:05 UTC by SollyJ

# 개인 롤링페이퍼 생성 및 조회 의존성 주입
**Controller ↔️ Service Layer ↔️ Data Access layer**
여기서는 각각 api/routes디렉토리, services디렉토리, interfaces디렉토리를 의미한다.

- Controller는 Service를 주입받는다.
<img width="550" alt="routes와 services" src="https://user-images.githubusercontent.com/68101656/211197031-cab3dcbe-54e3-4f61-83a7-39c6be1b3663.png">
- Service는 DTO를 주입받는다.
<img width="383" alt="스크린샷 2023-01-08 오후 9 56 06" src="https://user-images.githubusercontent.com/68101656/211197159-52ae0c95-e1f5-485b-8eff-53c427d45054.png">

## 개인 롤링페이퍼 생성
Postman으로 post했을때 결과
<img width="1291" alt="페이퍼생성 db" src="https://user-images.githubusercontent.com/68101656/211196564-a837bb9f-c0a2-4b9d-b45a-718201f679a1.png">

## 개인 롤링페이퍼 조회
### 시행착오
<img width="1291" alt="페이퍼 조회 에러" src="https://user-images.githubusercontent.com/68101656/211196873-93d2f747-7147-43a1-be74-5f84974c3947.png">
파라미터를 잘 넣어주어도 undefined되었다는 에러가 계속 떴다.<br/>
알고보니 api의 파라미터 paperid와 DTO변수명이 달라서 그런 것이었다.<br/>

<img width="991" alt="스크린샷 2023-01-08 오후 9 32 20" src="https://user-images.githubusercontent.com/68101656/211197376-6fe660f0-106f-4286-b3b3-5263564e784d.png">
api의 파라미터명과 DTO변수명을 맞춰주니 결과가 잘 나왔다.<br/>

하지만 기본적으로 [REST API에는 소문자를 넣는 것이 적합](https://meetup.nhncloud.com/posts/92)하다고 알고있는데 이를 어떻게 해야할지 의문이다.🤔

2023-01-08 14:24 UTC, Hyyena commented on src/api/routes/v1/individual.ts
> +    "/papers/:personalRollingPaperId",
API 명세서대로 `/papers/:paperId`로 수정해야 할 것 같습니다.

2023-01-08 14:26 UTC, Hyyena commented on src/interfaces/PersonalRollingPaper.ts
> +  public_type: boolean;
camelCase를 사용하는 것이 어떤가요?

2023-01-08 14:27 UTC, Hyyena commented on src/interfaces/PersonalRollingPaper.ts
> +  personalRollingPaperId: string;
API 명세서대로 path parameter를 고치면 이 DTO의 키 값도 `paperId`로 변경돼야 할 것 같습니다.

2023-01-08 14:27 UTC, Hyyena commented on src/interfaces/PersonalRollingPaper.ts
> +  public_type: boolean;
camelCase를 사용하는 것이 어떤가요?

2023-01-08 14:28 UTC, Hyyena commented on src/services/individual.ts
> +import { getSystemErrorMap } from "util";
자동완성으로 잘못 추가된 것 같습니다.

2023-01-08 14:35 UTC, Hyyena commented on src/services/individual.ts
> +  // ? 아마 title, public_type만 수정할수있을듯
기능명세서 상으로는 제목만 수정 가능하긴 한데, 공개/비공개에 대한 수정도 가능하면 좋을 것 같습니다. (로직이 얼마나 추가될지는 모르겠네여..)

2023-01-08 14:36 UTC, Hyyena requested changes
고생고생 👍

2023-01-08 14:43 UTC, Hyyena commented
Data Access Layer는 데이터베이스에 직접적으로 접근하는 계층이니까 저희 프로젝트 기준 서비스 로직 코드에서 수행되는 Sequelize가 Data Access Layer를 담당하고 있는 것 같습니다.
DTO는 각 레이어 간의 정보 전달을 목적으로 생성된 객체라고 봐야할 것 같습니다.

URL에서 path parameter는 camelCase를 사용하고, DTO도 이에 맞춰서 사용하면 될 것 같습니다.

2023-01-08 23:58 UTC, wodb73 approved these changes

2023-01-09 06:03 UTC, SollyJ commented on src/services/individual.ts
> +  // ? 아마 title, public_type만 수정할수있을듯
수정부분은 아직 틀만 만들어놓은 미완성상태입니다. 반영해보겠습니다!

2023-01-09 08:05 UTC, Hyyena approved these changes
고생했으요 🤝

2023-01-09 09:27 UTC, j2woo approved these changes

2023-01-09 09:28 UTC, merged