🗃️feat(db): design schema
woocheonjae/HiRolling-Server pull request #9
Opened 2022-12-26 12:54 UTC by Hyyena

# Design schema in the models directory

## 1. ERD

![image](https://user-images.githubusercontent.com/70932170/209551186-7189fc91-de06-459c-b3d3-8502720ef7de.png)

![image](https://user-images.githubusercontent.com/70932170/209551239-7caf824a-f53d-45ea-94fc-8a252ece0584.png)

close #8

2022-12-26 14:05 UTC, Hyyena commented
PR 올리고보니 첨부 이미지 테이블 이름들이 camelCase네여 수정해야 할 것 같아여

2022-12-26 14:21 UTC, Hyyena reviewed
개인 포스트 첨부 이미지 테이블과 그룹 포스트 첨부 이미지 테이블 네이밍이 **snake_case**가 아닌 **camelCase**로 작성돼있습니다.

2022-12-26 15:29 UTC, SollyJ requested changes

2022-12-26 15:29 UTC, SollyJ commented on src/models/groupPostAttachedImage.js
> +        tableName: "groupPostAttachedImage",
group_post_attached_image로 수정해야 할 것 같습니다.

2022-12-26 15:29 UTC, SollyJ commented on src/models/personalPostAttachedImage.js
> +        tableName: "personalPostAttachedImage",
personal_post_attached_image로 수정해야 할 것 같습니다.

2022-12-26 15:29 UTC, SollyJ commented on src/models/groupRollingPaper.js
> +    // GroupRollingPaper(1) : groupMember(1)
많이 헷갈렸던 부분이니까 주석을 더 추가했으면 좋겠습니다.

그룹 구성원은 그룹 롤링페이퍼에 속해있다. 즉, 그룹 롤링페이퍼와 그룹구성원은 부모와 자식 관계이다.
따라서 GroupRollingPaper.hasOne(db.GroupMember)인 것이고, 둘 테이블을 연결시켜주는 sourceKey는 groupRollingPaperId이다.

2022-12-26 15:29 UTC, SollyJ commented on src/models/groupMember.js
> +      // 1:1 관계에서 belongsTo로 연결하면 GroupMember에 groupRollingPaperId가 들어감
많이 헷갈렸던 부분이니까 주석을 더 추가했으면 좋겠습니다.

그룹 구성원은 그룹 롤링페이퍼에 속해있다.
따라서 GroupMember.belongsTo(db.GroupRollingPaper)이고, 그룹 구성원 테이블은 group_rolling_paper_id키를 외래키로 참조하며 targetting한다.

2022-12-26 23:45 UTC, Hyyena commented on src/models/groupPostAttachedImage.js
> +        tableName: "groupPostAttachedImage",
수정 완료했습니다!

2022-12-26 23:45 UTC, Hyyena commented on src/models/personalPostAttachedImage.js
> +        tableName: "personalPostAttachedImage",
수정 완료했습니다!

2022-12-26 23:46 UTC, Hyyena commented on src/models/groupRollingPaper.js
> +    // GroupRollingPaper(1) : groupMember(1)
추가 설명 달았습니다!

2022-12-26 23:46 UTC, Hyyena commented on src/models/groupMember.js
> +      // 1:1 관계에서 belongsTo로 연결하면 GroupMember에 groupRollingPaperId가 들어감
추가 설명 달았습니다!

2022-12-27 00:16 UTC, SollyJ approved these changes

2022-12-27 00:51 UTC, j2woo approved these changes

2022-12-27 01:00 UTC, wodb73 approved these changes

2022-12-27 01:00 UTC, wodb73 approved these changes
good!~!~!

2022-12-27 02:07 UTC, wodb73 reviewed
good~

2022-12-27 03:08 UTC, j2woo approved these changes

2022-12-27 03:09 UTC, SollyJ approved these changes

2022-12-27 03:09 UTC, j2woo approved these changes

2022-12-27 03:09 UTC, SollyJ approved these changes

2022-12-27 03:09 UTC, wodb73 approved these changes

2022-12-27 03:10 UTC, SollyJ approved these changes

2022-12-27 03:10 UTC, wodb73 approved these changes

2022-12-27 05:01 UTC, SollyJ reviewed
merge 해주세요

2022-12-27 05:02 UTC, merged